import { AudiencePage } from "@/components/AudiencePage";
import { KeyRound, Smartphone, DatabaseBackup, MessageCircleWarning } from "lucide-react";
export const metadata = {title:"Para você",description:"MJ Proteção Digital: orientação para contas, celular, privacidade e prevenção de golpes, com atendimento remoto e respeito aos seus dados."};
export default function Page() { return <AudiencePage singleLineTitle resources={{title:"Recursos oficiais para sua proteção",intro:"Conheça serviços que podem complementar seus cuidados digitais. A MJ INFO orienta; a ativação e o uso acontecem nos canais oficiais.",items:[{name:"Conta GOV.BR",text:"Identidade digital para acessar serviços públicos. Conheça as orientações oficiais de segurança da sua conta.",url:"https://www.gov.br/governodigital/pt-br/identidade/conta-gov-br"},{name:"BC Protege+",text:"Serviço do Banco Central para restringir a abertura de contas correntes, poupança e contas de pagamento pré-pagas em seu nome. Consulte as condições oficiais.",url:"https://www.bcb.gov.br/meubc/bcprotege"},{name:"Celular Seguro",text:"Programa para comunicar ocorrências e solicitar medidas de bloqueio aos participantes. Conheça as opções e os efeitos antes de usar.",url:"https://www.gov.br/anatel/pt-br/assuntos/celular-legal/celular-seguro"}],note:"Referências informativas a serviços oficiais. A MJ INFO não representa o Governo Federal ou o Banco Central e não solicita credenciais desses serviços."}} label="Para você · MJ Proteção Digital" title="Sua vida digital merece cuidado e clareza." intro="Contas, fotos, conversas e documentos fazem parte da sua vida. Ajudamos você a organizar acessos e reduzir riscos com orientação especializada e linguagem simples." items={[
 {icon:KeyRound,title:"Contas e acessos",text:"Revisão de segurança de e-mail e redes sociais, autenticação em duas etapas e organização de senhas."},
 {icon:Smartphone,title:"Celular e privacidade",text:"Orientação sobre configurações, permissões de aplicativos e cuidados com informações pessoais."},
 {icon:DatabaseBackup,title:"Arquivos importantes",text:"Orientação para cópias de segurança de fotos e documentos e planejamento para perda ou troca de dispositivo."},
 {icon:MessageCircleWarning,title:"Golpes e perda de acesso",text:"Ajuda para avaliar situações suspeitas e seguir os canais oficiais de recuperação. O resultado depende do caso e da plataforma."}
 ]} extra={{title:"Atendimento com respeito à sua privacidade",text:"O trabalho é combinado com você e realizado com sua autorização. Não envie senhas, códigos de autenticação ou dados bancários na primeira mensagem."}} note="Explique a situação sem compartilhar informações sensíveis. Vamos avaliar como podemos ajudar." message="Olá, quero orientação sobre proteção digital pessoal."/>; }


