import { AudiencePage } from "@/components/AudiencePage";
import { HeartHandshake, Gamepad2, ShieldCheck, MessagesSquare } from "lucide-react";
export const metadata = {title:"Para sua família",description:"Orientação para pais e adolescentes sobre privacidade, jogos, redes sociais e segurança digital, com diálogo e respeito."};
export default function Page() { return <AudiencePage resources={{title:"Ferramentas que apoiam o acompanhamento",intro:"Podemos orientar a escolha e a configuração de recursos de tempo de uso, supervisão e relatórios, conforme os dispositivos e os combinados da família.",items:[{name:"Google Family Link",text:"Gerenciamento de aplicativos, tempo de uso e configurações de contas supervisionadas em dispositivos compatíveis.",url:"https://families.google/intl/pt-BR/familylink/"},{name:"Apple Screen Time · Tempo de Uso",text:"Informações de uso e ajustes de limites no ecossistema Apple, com recursos de Compartilhamento Familiar.",url:"https://support.apple.com/pt-br/guide/security/secd8831e732/web"},{name:"Qustodio",text:"Controle parental com relatórios de atividade e limites. Recursos disponíveis variam conforme plano e dispositivo.",url:"https://www.qustodio.com/pt-br/product-features/"},{name:"Kaspersky Safe Kids",text:"Recursos de controle parental, uso de aplicativos e relatórios conforme a plataforma e a versão contratada.",url:"https://www.kaspersky.com.br/safe-kids/features"}],note:"Ferramentas de terceiros apresentadas como referência, sem vínculo de parceria oficial. Compatibilidade, planos e recursos devem ser conferidos com o fornecedor. Acompanhamento transparente, com diálogo e respeito à privacidade."}} label="Para sua família · MJ Proteção Digital" title="Mais segurança online. Mais diálogo em família." intro="Orientação para pais e adolescentes usarem a tecnologia com cuidado, autonomia e responsabilidade. A proteção combina configurações e conversa, respeitando a idade e a realidade de cada família." items={[
 {icon:HeartHandshake,title:"Orientação para pais",text:"Entender as ferramentas, combinar limites e acompanhar a rotina digital sem depender de tentativa e erro."},
 {icon:Gamepad2,title:"Jogos e redes sociais",text:"Cuidados com exposição, contatos desconhecidos, compras e golpes em jogos e plataformas sociais."},
 {icon:ShieldCheck,title:"Configurações de proteção",text:"Orientação sobre privacidade, contas, controle parental e tempo de tela. As ferramentas são apoio; não substituem o acompanhamento familiar."},
 {icon:MessagesSquare,title:"Um espaço para adolescentes",text:"Conversas sobre identidade digital, respeito, segurança de contas e o que fazer diante de situações desconfortáveis. Proteção sem vigilância escondida."}
 ]} note="Conte quais são as dúvidas da sua família e a faixa etária dos filhos. Vamos combinar um atendimento adequado." message="Olá, quero orientação de proteção digital para minha família."/>; }

